### ISSUE TITLE
Should cell cycle regression should include scaling of all genes?

### ISSUE THREAD

**Issue by derrik-gratz** [yerkes-gencore/gencoreSC#71]
Vignette always has `scaleData(obj, features = rownames(obj)`, rather than just working on variable features. As I understand it, you don't know if a feature is going to be variable until after the regression, so you should scale all genes and recalculate your variable features before proceeding to PCA etc.

https://satijalab.org/seurat/articles/cell_cycle_vignette.html

**Comment by derrik-gratz** [comment]
Perhaps you don't need to recalculate variable features prior to PCA after regression, as they don't in the vignette. I guess with the assumption that the non-variable ones won't be included in high PCs. But I think the point remains about scaling all genes, and I think due diligence would be to recalculate variable features after scaling everything with regression.

**Comment by micahpf** [comment]
Based on the source code for `Seurat::CellCycleScoring()` and `Seurat::AddModuleScore`, I think it's just using the `data` slot, not the `scale.data` slot and I think it looks at all features, not just variable features. In that case, how you scale the data and find variable features is downstream and has no effect on the cell cycle scoring.

`Seurat::ScaleData()` only adds/overwrites the `scale.data` slot, whereas `Seurat::FindVariableFeatures()` uses the `data` slot as input so again there should be no effect of cell cycle regression on which features are deemed variable.

I think their use of all genes in the vignette was irrelevant to cell cycle regression, perhaps just something they were doing because it was a small dataset? So I think our current workflow in `NormFindVarScaleData()` is correct.

**Comment by derrik-gratz** [comment]
I feel like we'd want the PCs to be calculated using the variable features calculated after CC regression, in the event a highly variable gene(s) were tied to CC?

**Comment by micahpf** [comment]
But I think cc regression with `ScaleData()` only outputs into the `scale.data` slot whereas `FindVariableFeatures()` takes the `data` slot as input so, re-finding variable features won't be using info from cc regression.

**Comment by derrik-gratz** [comment]
Yeah, looking at their vignette, It doesn't look like they recalculate variable genes after regression, but conceptually it feels like we should. I guess the assumption is that if you have 2-3k variable genes and some hundred of those become uninformative, you still have 1.5-2.5k to inform PCA

**Comment by micahpf** [comment]
```
pbmc_small <- pbmc_small %>% NormalizeData() # input: 'counts' slot; output: 'data' slot
pbmc_small <- pbmc_small %>% CellCycleScoring() # input: 'data' slot; output: metadata (adds some module scores)
pbmc_small <- pbmc_small %>% FindVariableFeatures() # input: 'data' slot; output: 'var.feaures' slot
pbmc_small <- pbmc_small %>% ScaleData() # input: 'data' slot (using genes in 'var.features' slot as default); output: 'scale.data' slot
pbmc_small <- pbmc_small %>% RunPCA() # input: 'scale.data' slot (using genes in 'var.features' slot as default); output: 'pac' DimReduc object in 'reductions' slot
```

**Comment by micahpf** [comment]
I see what you mean. But I guess the way they've set it up there's no way to re-evaluate how variable a gene is based on information about how it scales / is corrected by regressing out features etc.

**Comment by micahpf** [comment]
The more I learn about Seurat (and developing packages) the more I feel like they are severely lacking clarity in their documentation and vignettes that causes a lot of people to get really confused and/or misuse their tools/workflow.

**Comment by derrik-gratz** [comment]
Final answer: no!

Variable feature identification doesn't use scale.data slot, so the CC regression will not affect the identification of variable features for dim. reduction

https://github.com/satijalab/seurat/issues/2313
